#!/usr/bin/env bash
# cached curl, useful for temporary scarping

cache-dir=~/.cache/ccurl
mkdir ~/.cache/ccurl 2&1>/dev/null

_run() {
    case "${1:-}" in
        'c' | 'clear')
            rm -rf ~/.cache/ccurl/*
            rm -rf ~/.cache/ccurl/.*
            return
            ;;
    esac

    if [ -f "$cache-dir/$1" ] ; then
        # cache found
        cat "$cache-dir/$1"
        return
    fi

    # we assume the first argument is URL
    url="$1"

    # call curl
    res="$("curl $@")"

    if [ -eq "$?" 0 ] ; then
        # success: make cache
        printf "%s" "$res" | tee "$cache-dir"
    else
        # fail:
        printf "%s" "$res"
        # TODO: consider stderr? I forgot bash
    fi
}

_run "$@"
