#!/usr/bin/env -S bash -euE
#
# Delete and register all the albums in `cmus`.

# TODO: Better command?
seq 0 200 | xargs -I{} cmus-remote -C 'win-remove'

cmus-remote -C "add $HOME/Resources/music"
# cmus-remote -C "add $HOME/podcast"

cmus-remote -C 'update-cache'

