#!/usr/bin/env bash

cat << EOS | runghc
import Control.Applicative
import Control.Monad
import Data.Char
import Data.Bits
import Data.List
import Data.Maybe
import Data.Ord
import GHC.Float (int2Float)
import System.IO
import Text.Printf

main = do
    print \$ $1
EOS

