#!/usr/bin/env bash
#
# Removes frontmatter and code block from ordinary markdown

# TODO: exclude link URLs

cat "$@" |
    # TODO: delete only the first one
    sed "/^---/,//d" |
    sed '/^```/,//d'

