#!/usr/bin/env bash
#
# `wc -l` per Rust module with limited support.
# It assuems use of `mod.rs` and max depth as `src/dir/file.rs`.

for x in src/* ; do
    if [ -f "$x" ] ; then
        wc -l "$x" | awk '{printf("%s\t%s\n", $2, $1)}'
        continue
    fi

    if [ -d "$x" ] ; then
        printf '%s\t' "$x"
        wc -l "$x"/*.rs | sed '$d' | awk '{sum+=$1;} END {print sum;}'
    fi
done | column -t

printf 'total\t\t%s' "$(fd -e rs . src | xargs wc -l | tail -n 1 | awk '{print $1}')"

