#!/usr/bin/env bash

# xdpyinfo | grep resolution
# => 203x203

# set dpi globally:
# $ xrandr --dpi 162

# xrandr --output HDMI-0 --off --output DP-1 --off

xrandr --output DP-1 --primary --mode 3840x2160

xrandr --output HDMI-0 --left-of DP-1 --mode 1920x1080
# xrandr --output HDMI-0 --rotate left
xrandr --dpi 163

