#!/usr/bin/env bash
#
# Take screen shot on X11 using `imagemagick`:
# https://unix.stackexchange.com/questions/233345/how-can-i-easily-make-screenshots-of-screen-regions-on-arch-linux-with-i3-wm

set -euE
set -o pipefail

if [ $# -eq 0 ] ; then
    show_help
    exit
fi

base_folder="${2:-$(pwd)}"
outpath="${base_folder}/$(date '+%Y-%m-%d_%H-%M-%S').png"

if [ "${1}" == '-w' ] ; then
    # capture a window
    import -window root "${outpath}"
elif [ "${1}" == '-r' ] ; then
    # capture a user-selected region
    import "${outpath}"
else
    echo "specify -w (window) or -r (region)" 1>&2
fi

xclip -selection clipboard -target image/png -i < "${outpath}"

