#!/usr/bin/env -S bash -euE

IFS=$'\n\t'
dir=""

root="$HOME/write/zenn"

if [ "$#" -ne 1 ] ; then
    # on no argument
    dir="$(fd -a --max-depth 1 . "$root/books" | fzf)"
else
    # on given book directory
    dir="$(cd "$1" ; pwd)"
fi


chapters="$(cat "$dir/config.yaml" | grep '^  - ' | sed 's;^  - ;;g')"
for name in $chapters ; do
    file="$dir/$name.md"
    cat "$file" | grep -e '^#' -e '^title:'
    printf '\n'
done

